### ISSUE TITLE
Addition of Zipcode to addresses needed.

### ISSUE THREAD

**Issue by SuhasHareesh** [feder-cr/Auto_Jobs_Applier_AIHawk#407]
If there was a way to add zipcode to addresses it would be amazing. But, I tried to do it and found out that the lib folder is an external library and users can't make any changes to it.

**Comment by thomHayner** [comment]
@SuhasHareesh thanks, I noticed some issues with addresses as well.

It probably needs to be standardized to an international format that recognizes things like provinces alongside states, as well as zip codes and their counterpart postal codes in other locales.

Then it also needs to be considered alongside LinkedIn's format for locations, which is weird and wonky due to LinkedIn's internals that we can't control but have to work with.

**Comment by RushiChaganti** [comment]
I'm working on this part i will update you when i am finished with the changes
