### ISSUE TITLE
[FEATURE]: Simulation mode

### ISSUE THREAD

**Issue by RichP-fr** [feder-cr/Auto_Jobs_Applier_AIHawk#519]
### Feature summary

Run the bot in "simulation" mode, i.e. doing all the steps except applying for real

### Feature description

In simulation mode, the bot would build the resume & cover letter, and save them to a directory along with the job posting URL. That would allow for further fine-tuning / debug before using it "for real".

### Motivation

Debugging & improving code ; testing in languages other than English

### Additional context

I would gladly help & start this work if someone gives me a starting point. Thanks!

**Comment by Olivier222** [comment]
I agree with this. Ultimately I think the "simulation" should be part of the test suites as a way to confirm your own setup.

I went through the code flow and I think I found the code block that clicks the actual submit button [here](https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/blob/a11381f4b838f489e9b80c42ae4ed6b04b3b862c/src/aihawk_easy_applier.py#L287C8-L287C48) 

```
if 'submit application' in button_text
```

A good place to start could be to add some logic that would avoid clicking on the submit button and instead do something similar to "click cancel". We would also need to add logic that saves all the generations to a folder specific to each job application. 

Also, we could still apply to the jobs manually after we reviewed the generated job application. Or instead of manually, we have another script that submits the job applications after we reviewed, edited and approved them.

**Comment by feder-cr** [comment]
Guys,can you work on this?

**Comment by RichP-fr** [comment]
Sure, I'm not a python developer, but I'll start with the help of AI :)

Also I'll work on adding the option of having several languages.

Talk soon

**Comment by feder-cr** [comment]
@Olivier222 @RichP-fr  join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity
